### ISSUE TITLE
TypeError: ts.createIncrementalCompilerHost is not a function

### ISSUE THREAD

**Issue by aelbore** [analogjs/analog#2020]
### Please provide the environment you discovered this bug in.

clone this repo 
https://github.com/aelbore/angular-to-analogjs-migration-repo

### Which area/package is the issue in?

create-analog

### Description

version 2.2.0 having `TypeError: ts.createIncrementalCompilerHost is not a function`
when i execute npx vite
it works fine with version 2.1.0 

as I checked - 
in version 2.2.0 typescript was import as 
`import * as ts from "typescript"` /// which has error

while in version 2.1.0 it was import as
const require = createRequire(import.meta.url)
const ts = require("typescript")

### Please provide the exception or error you saw

```true
TypeError: ts.createIncrementalCompilerHost is not a function
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No
